#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use BeechIt\JsonToCodeClimateSubsetConverter\ConverterCommand;

$application = new Application();

$application->add(new ConverterCommand);

$application->run();
