name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - 7.3
          - 7.4
        suite:
          - infection-ci
          - phan
          - php-cbf
          - phpcs
          - phplint
          - phpstan
          - phpunit
          - psalm

    name: PHP ${{ matrix.php }} testing ${{ matrix.suite }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}-${{ matrix.php }}
          restore-keys: ${{ runner.os }}-composer-${{ matrix.php }}-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run ${{ matrix.suite }}
        run: composer ${{ matrix.suite }}
