name: Run PHPStan

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.3, 7.4]
        dependencies: [lowest, highest]

    steps:
    - uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run PHPStan
      run: composer phpstan
